
function q(id){return document.getElementById(id)}
function fmt(n,dec){return Number(n).toLocaleString('pt-PT',{minimumFractionDigits:dec,maximumFractionDigits:dec})}

export function buildCumul(rows){ const svg=q('chartCumul'); while(svg.firstChild) svg.removeChild(svg.firstChild); const togg=q('seriesToggles'); if(!togg) return; togg.innerHTML=''; if(!rows.length) return; const anos=+document.getElementById('anos').value||10; const meses=anos*12; const series=rows.map(r=>({key:r.key,name:r.name,m_tco:r.tco_mes_n,color:r.comp_col})); series.forEach((s,idx)=>{ const lab=document.createElement('label'); lab.className='row'; const cb=document.createElement('input'); cb.type='checkbox'; cb.checked=(idx<5); cb.dataset.key=s.key; const span=document.createElement('span'); span.textContent=' '+s.name; const chip=document.createElement('span'); chip.style.background=s.color; chip.style.display='inline-block'; chip.style.width='12px'; chip.style.height='12px'; chip.style.borderRadius='50%'; chip.style.marginLeft='6px'; lab.appendChild(cb); lab.appendChild(span); lab.appendChild(chip); togg.appendChild(lab); cb.onchange=draw; });
  function mapX(m,w,pL,pR){ return pL + (w-pL-pR)*m/meses }
  function draw(){ while(svg.firstChild) svg.removeChild(svg.firstChild); const w=svg.clientWidth||svg.getBoundingClientRect().width; const h=svg.clientHeight||320; const pL=52,pR=60,pT=18,pB=32; const x0=pL,x1=w-pR,y0=h-pB,y1=pT; const active=series.filter(s=>{ const el=[...togg.querySelectorAll('input')].find(i=>i.dataset.key===s.key); return el?el.checked:true; }); let ymax=0; active.forEach(s=>{ const val= s.m_tco*meses; if(val>ymax) ymax=val; }); if(ymax<=0) ymax=1; const ns='http://www.w3.org/2000/svg'; for(let g=0; g<=5; g++){ const v=ymax*g/5; const gy=document.createElementNS(ns,'line'); gy.setAttribute('x1',x0); gy.setAttribute('y1',y0 - (y0-y1)*(v/ymax)); gy.setAttribute('x2',x1); gy.setAttribute('y2',y0 - (y0-y1)*(v/ymax)); gy.setAttribute('stroke','var(--grid)'); gy.setAttribute('stroke-width','1'); gy.setAttribute('stroke-dasharray','3,3'); svg.appendChild(gy); const ty=document.createElementNS(ns,'text'); ty.setAttribute('x',x0-6); ty.setAttribute('y',y0 - (y0-y1)*(v/ymax) - 2); ty.setAttribute('font-size','11'); ty.setAttribute('fill','#64748b'); ty.setAttribute('text-anchor','end'); ty.textContent=Math.round(v).toLocaleString('pt-PT'); svg.appendChild(ty); }
    for(let m=0;m<=meses;m+=12){ const gx=document.createElementNS(ns,'line'); const xx=mapX(m,w,pL,pR); gx.setAttribute('x1',xx); gx.setAttribute('y1',y0); gx.setAttribute('x2',xx); gx.setAttribute('y2',y1); gx.setAttribute('stroke','var(--grid)'); gx.setAttribute('stroke-width','1'); gx.setAttribute('stroke-dasharray','3,3'); svg.appendChild(gx); const tx=document.createElementNS(ns,'text'); tx.setAttribute('x',xx); tx.setAttribute('y',y0+18); tx.setAttribute('font-size','11'); tx.setAttribute('fill','#64748b'); tx.setAttribute('text-anchor','middle'); tx.textContent=m; svg.appendChild(tx); }
    active.forEach(s=>{ const pts=[]; let lastX=mapX(0,w,pL,pR), lastY=y0; for(let m=0;m<=meses;m+=1){ const x=mapX(m,w,pL,pR); const y=y0 - (y0-y1)*((s.m_tco*m)/(ymax)); pts.push(x+','+y); lastX=x; lastY=y; } const poly=document.createElementNS(ns,'polyline'); poly.setAttribute('fill','none'); poly.setAttribute('stroke',s.color); poly.setAttribute('stroke-width','2.2'); poly.setAttribute('points',pts.join(' ')); svg.appendChild(poly); const lbl=document.createElementNS(ns,'text'); lbl.setAttribute('x',lastX+6); lbl.setAttribute('y',lastY+4); lbl.setAttribute('font-size','12'); lbl.setAttribute('fill',s.color); lbl.textContent=s.name+' · '+fmt(s.m_tco*meses,0); svg.appendChild(lbl); });
  }
  window.__exportPNG = ()=>{ try{ const xml=new XMLSerializer().serializeToString(svg); const svgBlob=new Blob([xml],{type:'image/svg+xml;charset=utf-8'}); const url=URL.createObjectURL(svgBlob); const img=new Image(); img.onload=function(){ const canvas=document.createElement('canvas'); canvas.width=svg.clientWidth||svg.getBoundingClientRect().width; canvas.height=svg.clientHeight||320; const ctx=canvas.getContext('2d'); ctx.fillStyle=getComputedStyle(svg).backgroundColor||'#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.drawImage(img,0,0); canvas.toBlob(function(blob){ const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='custo_cumulado_v8.png'; a.click(); },'image/png'); URL.revokeObjectURL(url); }; img.src=url; }catch(e){ alert('Falha no export PNG'); } };
  draw();
}

export function buildCompare(rows){ const svg=q('chartCompare'); if(!svg) return; while(svg.firstChild) svg.removeChild(svg.firstChild); if(!rows.length) return; let sel=[...q('cmpSel').selectedOptions].map(o=>o.value); if(sel.length===0){ sel=rows.slice(0,3).map(r=>r.key); }
  const metric=q('cmpMetric').value||'tco_km_n'; const stack=q('cmpStack').checked; const chosen=rows.filter(r=> sel.includes(r.key)).slice(0,3);
  const ns='http://www.w3.org/2000/svg'; const w=svg.clientWidth||svg.getBoundingClientRect().width; const h=svg.clientHeight||320; const pL=70,pR=24,pT=20,pB=44; const x0=pL,x1=w-pR,y0=h-pB,y1=pT;
  let maxv=0; if(stack){ chosen.forEach(r=>{ const v=r.eurCapex_n + (r.eur100_n/100) + ((r.fixos_m*12)/((+document.getElementById('kmAno').value||10000))); if(v>maxv) maxv=v; }); } else { chosen.forEach(r=>{ const v=r[metric]; if(v>maxv) maxv=v; }); }
  if(maxv<=0) maxv=1; const mapX=v=> x0 + (x1-x0)*v/maxv;
  const ax=document.createElementNS(ns,'line'); ax.setAttribute('x1',x0); ax.setAttribute('y1',y0); ax.setAttribute('x2',x0); ax.setAttribute('y2',y1); ax.setAttribute('stroke','#718096'); ax.setAttribute('stroke-width','1'); svg.appendChild(ax); const ay=document.createElementNS(ns,'line'); ay.setAttribute('x1',x0); ay.setAttribute('y1',y0); ay.setAttribute('x2',x1); ay.setAttribute('y2',y0); ay.setAttribute('stroke','#718096'); ay.setAttribute('stroke-width','1'); svg.appendChild(ay);
  const barH=28, gap=18; chosen.forEach((r,idx)=>{ const y=y0 - (barH+gap)*(chosen.length-1-idx); const color=r.comp_col; if(!stack){ const v=r[metric]; const x=mapX(v); const rect=document.createElementNS(ns,'rect'); rect.setAttribute('x',x0); rect.setAttribute('y',y); rect.setAttribute('width',Math.max(2,x-x0)); rect.setAttribute('height',barH); rect.setAttribute('fill',color); rect.setAttribute('rx',6); svg.appendChild(rect); const tx=document.createElementNS(ns,'text'); tx.setAttribute('x',x0-8); tx.setAttribute('y',y+barH/2+4); tx.setAttribute('text-anchor','end'); tx.setAttribute('font-size','12'); tx.setAttribute('fill','#64748b'); tx.textContent=r.marca+' '+r.modelo; svg.appendChild(tx); const dec=(metric==='tco_mes_n'?0:(metric==='tco_km_n'?3:2)); const tv=document.createElementNS(ns,'text'); tv.setAttribute('x',x+6); tv.setAttribute('y',y+barH/2+4); tv.setAttribute('font-size','12'); tv.setAttribute('fill','#334155'); tv.textContent=fmt(v,dec); svg.appendChild(tv); }
    else {
      const v_cap=r.eurCapex_n; const v_energy=r.eur100_n/100; const v_fix=(r.fixos_m*12)/((+document.getElementById('kmAno').value||10000));
      const x1s=x0; const x2s=mapX(v_cap); const rect1=document.createElementNS(ns,'rect'); rect1.setAttribute('x',x1s); rect1.setAttribute('y',y); rect1.setAttribute('width',Math.max(2,x2s-x1s)); rect1.setAttribute('height',barH); rect1.setAttribute('fill','#60a5fa'); rect1.setAttribute('rx',6); svg.appendChild(rect1);
      const x3s=mapX(v_cap+v_energy); const rect2=document.createElementNS(ns,'rect'); rect2.setAttribute('x',x2s); rect2.setAttribute('y',y); rect2.setAttribute('width',Math.max(2,x3s-x2s)); rect2.setAttribute('height',barH); rect2.setAttribute('fill','#34d399'); svg.appendChild(rect2);
      const x4s=mapX(v_cap+v_energy+v_fix); const rect3=document.createElementNS(ns,'rect'); rect3.setAttribute('x',x3s); rect3.setAttribute('y',y); rect3.setAttribute('width',Math.max(2,x4s-x3s)); rect3.setAttribute('height',barH); rect3.setAttribute('fill','#fbbf24'); rect3.setAttribute('rx',6); svg.appendChild(rect3);
      const tx2=document.createElementNS(ns,'text'); tx2.setAttribute('x',x0-8); tx2.setAttribute('y',y+barH/2+4); tx2.setAttribute('text-anchor','end'); tx2.setAttribute('font-size','12'); tx2.setAttribute('fill','#64748b'); tx2.textContent=r.marca+' '+r.modelo; svg.appendChild(tx2);
      const tv2=document.createElementNS(ns,'text'); tv2.setAttribute('x',x4s+6); tv2.setAttribute('y',y+barH/2+4); tv2.setAttribute('font-size','12'); tv2.setAttribute('fill','#334155'); tv2.textContent=fmt(v_cap+v_energy+v_fix,3); svg.appendChild(tv2);
      const legend=document.createElementNS(ns,'g'); const items=[{c:'#60a5fa',t:'Capex/km'},{c:'#34d399',t:'Energia/km'},{c:'#fbbf24',t:'Fixos/km'}]; const lx=x1-200, ly=y-60; items.forEach((it,i)=>{ const g=document.createElementNS(ns,'g'); const rct=document.createElementNS(ns,'rect'); rct.setAttribute('x',lx); rct.setAttribute('y',ly+i*18); rct.setAttribute('width','14'); rct.setAttribute('height','14'); rct.setAttribute('fill',it.c); rct.setAttribute('rx','3'); const tt=document.createElementNS(ns,'text'); tt.setAttribute('x',lx+20); tt.setAttribute('y',ly+i*18+12); tt.setAttribute('font-size','12'); tt.setAttribute('fill','#334155'); tt.textContent=it.t; g.appendChild(rct); g.appendChild(tt); legend.appendChild(g); }); svg.appendChild(legend);
    }
  });
  for(let k=0;k<=5;k++){ const v=maxv*k/5; const tx=document.createElementNS(ns,'text'); tx.setAttribute('x',mapX(v)); tx.setAttribute('y',y0+16); tx.setAttribute('font-size','11'); tx.setAttribute('fill','#64748b'); tx.setAttribute('text-anchor','middle'); tx.textContent=fmt(v, (metric==='tco_mes_n'?0:(stack?3:(metric==='tco_km_n'?3:2)))); svg.appendChild(tx); }
}
